export const CATOGARIES_ACTION_TYPE = {
  FETCH_CATOGARIES_START: "catogary/FETCH_CATOGARIES_START",
  FETCH_CATOGARIES_SUCCESS: "catogary/FETCH_CATOGARIES_SUCCESS",
  FETCH_CATOGARIES_FAILED: "catogary/FETCH_CATOGARIES_FAILED",
};
